Repository BiAPoL/napari-clusters-plotter, pull requests merged in 2025-05, with the labels that each got.

#394 remove tools-menu and skimage regionprops
  pyproject.toml
Labels: enhancement

#392 added clustering and dimensionality reduction to NAP6 menus
  src/napari_clusters_plotter/napari.yaml
Labels: documentation, enhancement

#390 Connect histogram optional features
  pyproject.toml
  src/napari_clusters_plotter/_new_plotter_widget.py
  src/napari_clusters_plotter/_tests/test_plotter.py
  src/napari_clusters_plotter/plotter_inputs.ui
Labels: enhancement

#401 Fix default color setting
  src/napari_clusters_plotter/_new_plotter_widget.py
  src/napari_clusters_plotter/_tests/test_plotter.py
Labels: bug

#403 extend algorithm subwidgets with links to docs
  docs/contributing/new_algorithm.md
  src/napari_clusters_plotter/_algorithm_widget.py
  src/napari_clusters_plotter/_dim_reduction_and_clustering.py
Labels: documentation, enhancement
